[package]
documentation = "https://gtk-rs.org/gtk3-rs/stable/latest/docs/gtk/"
categories = ["api-bindings", "gui"]
license = "MIT"
description = "Rust bindings for the GTK+ 3 library"
name = "gtk"
homepage = "https://gtk-rs.org/"
authors = ["The gtk-rs Project Developers"]
readme = "README.md"
version = "0.15.0"
keywords = ["gtk", "gtk-rs", "gnome", "GUI"]
repository = "https://github.com/gtk-rs/gtk3-rs"
build = "build.rs"
exclude = [
    "gir-files/*",
]
edition = "2021"
rust-version = "1.56"

[lib]
name = "gtk"

[features]
v3_20 = ["ffi/v3_20"]
v3_22 = ["v3_20", "ffi/v3_22", "gdk/v3_22"]
v3_22_20 = ["v3_22", "ffi/v3_22"]
v3_22_26 = ["v3_22_20", "ffi/v3_22_26"]
v3_22_27 = ["v3_22_26", "ffi/v3_22_27"]
v3_22_29 = ["v3_22_27", "ffi/v3_22_29"]
v3_22_30 = ["v3_22_29", "ffi/v3_22_30"]
v3_24 = ["v3_22_30", "ffi/v3_24"]
v3_24_1 = ["v3_24", "ffi/v3_24_1"]
v3_24_8 = ["v3_24_1", "ffi/v3_24_8"]
v3_24_9 = ["v3_24_8", "ffi/v3_24_9"]
dox = ["gdk/dox", "ffi/dox"]
gio_v2_58 = ["gio/v2_58"]

[package.metadata.docs.rs]
features = ["dox"]

[build-dependencies]
pkg-config = "0.3.7"

[dependencies]
libc = "0.2"
bitflags = "1.0"
field-offset = "0.3"
futures-channel = "0.3"
once_cell = "1.0"
atk = {path = "../atk", version = "0.15.0"}
ffi = {package = "gtk-sys", path = "sys", version = "0.15.0"}
gtk3-macros = {path = "../gtk3-macros", version = "0.15.0"}
cairo-rs = "0.15.0"
gio = "0.15.0"
glib = "0.15.0"
gdk = {path = "../gdk", version = "0.15.0"}
gdk-pixbuf = "0.15.0"
pango = "0.15.0"

[dev-dependencies]
gir-format-check = "^0.1"
