[build-dependencies]
pkg-config = "0.3.7"
system-deps = "6"

[dependencies]
libc = "0.2"

[dependencies.cairo]
package = "cairo-sys-rs"
version = "0.15.1"

[dependencies.gdk-pixbuf]
package = "gdk-pixbuf-sys"
version = "0.15.1"

[dependencies.gio]
package = "gio-sys"
version = "0.15.1"

[dependencies.glib]
package = "glib-sys"
version = "0.15.1"

[dependencies.gobject]
package = "gobject-sys"
version = "0.15.1"

[dependencies.pango]
package = "pango-sys"
version = "0.15.1"

[dev-dependencies]
shell-words = "1.0.0"
tempfile = "3"

[features]
v3_20 = []
v3_22 = ["v3_20"]
v3_24 = ["v3_22"]
dox = []

[lib]
name = "gdk_sys"

[package]
authors = ["The gtk-rs Project Developers"]
build = "build.rs"
description = "FFI bindings to libgdk-3"
homepage = "http://gtk-rs.org/"
keywords = ["gdk", "ffi", "gtk-rs", "gnome"]
license = "MIT"
links = "gdk-3"
name = "gdk-sys"
repository = "https://github.com/gtk-rs/gtk3-rs"
version = "0.15.1"
edition = "2021"
rust-version = "1.56"

[package.metadata.docs.rs]
features = ["dox"]

[package.metadata.system-deps.gdk_3_0]
name = "gdk-3.0"
version = "3.18"

[package.metadata.system-deps.gdk_3_0.v3_20]
version = "3.20"

[package.metadata.system-deps.gdk_3_0.v3_22]
version = "3.22"

[package.metadata.system-deps.gdk_3_0.v3_24]
version = "3.24"
